/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hanghoa;

import Business.BUS_Ban;
import Business.BUS_HangHoa;
import Business.BUS_HoaDon;
import Business.BUS_KhachHang;
import Business.BUS_Report;
import Business.BUS_TaiKhoan;
import Data.Ban;
import Data.KhachHang;
import Data.HangHoa;
import Data.HoaDon;
import Data.TaiKhoan;
import java.awt.Component;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author XoanXoan
 */
public class Lap_Hoa_Don_Ban_Hang extends javax.swing.JFrame {
    public static Lap_Hoa_Don_Ban_Hang it;
    private Component frame;
    /**
     * Creates new form LapHoaDon_Ban_Hang
     */
    double TongTien = 0;
    
    public Lap_Hoa_Don_Ban_Hang() {
        initComponents();
        loadDataHH();
        loadDataTaiKhoan();
        it= this;   
        t_SoLuong.setDocument(new DigitsDocument());
        t_DonGia.setDocument(new DigitsDocument());
        t_TySuatGTGT.setDocument(new DigitsDocument());
        
    }
    public void setData(String s, String y){
        t_MaCH.setText(s);
        t_TenCH.setText(y);
    }
    public void setData2(String a, String b, String c, String d){
        t_MaKH.setText(a);
        t_TenKH.setText(b);
        t_DiaChiKH.setText(c);
        t_MaSoThueKH.setText(d);
    }
    
    public class DigitsDocument extends PlainDocument { 
    public void insertString(int offs, String str, AttributeSet a) 
        throws BadLocationException 
    { 
        if(str==null) 
        { 
            return; 
        } 
        char[] addedFigures = str.toCharArray(); 
        char c; 
        for(int i=addedFigures.length; i>0; i--) 
        { 
            c=addedFigures[i-1]; 
            if(Character.isDigit(c)||c=='.') 
            { 
                super.insertString(offs, new String(new Character(c).toString()), a); 
            } 
        } 
    } 
    } 
    private void loadDataHH()
    {
       
        ArrayList<String> xx = new ArrayList<String>(); 
        xx = BUS_HangHoa.loadInfo();
        for(int i = 0; i < xx.size(); i++)
            cb_MaHang.addItem(xx.get(i));
    }
    private void loadDataTaiKhoan(){
        ArrayList<String> tk = new ArrayList<String>();
        tk = BUS_TaiKhoan.loadInfo();
        for(int i = 0; i<tk.size(); i++){
            cb_TaiKhoan.addItem(tk.get(i));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t_MaCH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_HangHoa = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        t_Tong = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        t_TongTien = new javax.swing.JTextField();
        btn_Thoat = new javax.swing.JButton();
        btn_LuaVaIn = new javax.swing.JButton();
        t_TinhGTGT = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        t_TienChu = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        t_TenCH = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        t_MaKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_TaoKH = new javax.swing.JButton();
        t_TenKH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        t_DiaChiKH = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        t_MaSoThueKH = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        t_SoHD = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tD_NgayBan = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        tD_NgayThanhToan = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        t_LyDo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        t_SoSeri = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        t_TySuatGTGT = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        t_TenTK = new javax.swing.JTextField();
        cb_TaiKhoan = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        t_TenHang = new javax.swing.JTextField();
        t_SoLuong = new javax.swing.JTextField();
        btn_ThemHang = new javax.swing.JButton();
        btn_XoaHang = new javax.swing.JButton();
        cb_MaHang = new javax.swing.JComboBox<>();
        btn_SửaHH = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        t_DonGia = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel1.setText("Mã kho/cửa hàng ");

        t_MaCH.setEditable(false);
        t_MaCH.setBackground(new java.awt.Color(204, 255, 255));
        t_MaCH.setForeground(new java.awt.Color(255, 0, 0));
        t_MaCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_MaCHActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("HÓA ĐƠN BÁN HÀNG");

        Tb_HangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hàng ", "Tên Mặt Hàng", "Đơn vị tính", "Số lượng", "Đơn giá bán", "Thành tiền "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tb_HangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_HangHoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tb_HangHoa);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel24.setText("Tiền thuế GTGT máy tính");

        t_Tong.setEditable(false);
        t_Tong.setBackground(new java.awt.Color(204, 255, 255));
        t_Tong.setForeground(new java.awt.Color(255, 0, 0));
        t_Tong.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t_Tong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_TongActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel26.setText("Tổng tiền ");

        t_TongTien.setEditable(false);
        t_TongTien.setBackground(new java.awt.Color(204, 255, 255));
        t_TongTien.setForeground(new java.awt.Color(255, 51, 0));
        t_TongTien.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t_TongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_TongTienActionPerformed(evt);
            }
        });

        btn_Thoat.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btn_Thoat.setText("Thoát ");
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });

        btn_LuaVaIn.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btn_LuaVaIn.setText("Lưu và in");
        btn_LuaVaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuaVaInActionPerformed(evt);
            }
        });

        t_TinhGTGT.setEditable(false);
        t_TinhGTGT.setBackground(new java.awt.Color(204, 255, 255));
        t_TinhGTGT.setForeground(new java.awt.Color(255, 0, 0));
        t_TinhGTGT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t_TinhGTGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_TinhGTGTActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel23.setText("Tổng tiền viết bằng chữ");

        t_TienChu.setEditable(false);
        t_TienChu.setBackground(new java.awt.Color(204, 255, 255));
        t_TienChu.setForeground(new java.awt.Color(255, 0, 0));

        jLabel29.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel29.setText("Tổng tiền viết bằng chữ:");

        t_TenCH.setEditable(false);
        t_TenCH.setBackground(new java.awt.Color(204, 255, 255));
        t_TenCH.setForeground(new java.awt.Color(255, 0, 0));
        t_TenCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_TenCHActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel4.setText("Mã khách");

        t_MaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_MaKHActionPerformed(evt);
            }
        });

        jLabel3.setText("Hoặc");

        btn_TaoKH.setText("Tạo mới");
        btn_TaoKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoKHActionPerformed(evt);
            }
        });

        t_TenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_TenKHActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel8.setText("Tên khách");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel11.setText("Địa chỉ");

        t_DiaChiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_DiaChiKHActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel14.setText("Mã số thuế");

        t_MaSoThueKH.setSize(111, 20);
        t_MaSoThueKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_MaSoThueKHActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel28.setText("Số hóa đơn");

        t_SoHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_SoHDActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel30.setText("Ngày bán ");

        tD_NgayBan.setDateFormatString("yyyy-MM-dd");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel18.setText("Ngày thanh toán ");

        tD_NgayThanhToan.setDateFormatString("yyyy-MM-dd");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel20.setText("Số seri");

        t_LyDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_LyDoActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel22.setText("Tài khoản");

        t_SoSeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_SoSeriActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel19.setText("Tỷ suất GTGT");

        t_TySuatGTGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_TySuatGTGTActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel21.setText("Lý do");

        t_TenTK.setEditable(false);
        t_TenTK.setBackground(new java.awt.Color(204, 255, 255));
        t_TenTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_TenTKActionPerformed(evt);
            }
        });

        cb_TaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TaiKhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(t_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_LyDo, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel28))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 12, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(t_SoHD)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_TaoKH)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t_DiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t_MaSoThueKH, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addGap(18, 18, 18)
                                        .addComponent(tD_NgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel18)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tD_NgayThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(t_SoSeri, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addGap(21, 21, 21)
                                .addComponent(t_TySuatGTGT, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TaoKH)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(t_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(t_DiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(t_MaSoThueKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tD_NgayThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tD_NgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(t_TySuatGTGT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(t_SoSeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(t_SoHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30))
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(t_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cb_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t_LyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(1178, 78));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel27.setText("Mã hàng");

        jLabel31.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel31.setText("Tên hàng");

        jLabel32.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel32.setText("Số lượng");

        t_TenHang.setEditable(false);
        t_TenHang.setBackground(new java.awt.Color(204, 255, 255));
        t_TenHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_TenHangActionPerformed(evt);
            }
        });

        t_SoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_SoLuongActionPerformed(evt);
            }
        });

        btn_ThemHang.setText("Thêm");
        btn_ThemHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemHangActionPerformed(evt);
            }
        });

        btn_XoaHang.setText("Xóa");
        btn_XoaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaHangActionPerformed(evt);
            }
        });

        cb_MaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_MaHangActionPerformed(evt);
            }
        });

        btn_SửaHH.setText("Sửa");
        btn_SửaHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SửaHHActionPerformed(evt);
            }
        });

        jLabel5.setText("Đơn giá bán");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_MaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_TenHang, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_ThemHang, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btn_SửaHH, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btn_XoaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(404, 404, 404))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(t_TenHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_MaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(t_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThemHang)
                    .addComponent(btn_XoaHang)
                    .addComponent(btn_SửaHH))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel33.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel33.setText("=");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_LuaVaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_MaCH, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(t_TenCH, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel29)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(t_TienChu, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel24)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(t_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t_TinhGTGT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(t_Tong, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(546, 546, 546)
                    .addComponent(jLabel23)
                    .addContainerGap(496, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(t_MaCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_TenCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(t_TienChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_Tong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_TinhGTGT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(t_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_LuaVaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(300, 300, 300)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(324, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t_MaCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_MaCHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_MaCHActionPerformed

    private void t_TongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_TongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_TongActionPerformed

    private void t_TongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_TongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_TongTienActionPerformed

    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        // TODO add your handling code here:
        Main a = new Main();
                a.setVisible(true);
                this.setVisible(false);
                this.dispose();
    }//GEN-LAST:event_btn_ThoatActionPerformed

    private void btn_LuaVaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuaVaInActionPerformed
        // TODO add your handling code here:
        //Lưu Hóa Đơn và Lưu Bán
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn lưu thông tin này?", "Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                if(t_MaCH.getText().equals("")||t_MaKH.getText().equals("")||t_SoHD.getText().equals("")||cb_TaiKhoan.getSelectedItem().toString().equals("")||tD_NgayBan.getDate().equals(null)||tD_NgayThanhToan.getDate().equals(null)||t_TySuatGTGT.getText().equals("")||t_SoSeri.getText().equals("")){
                    JOptionPane.showMessageDialog(frame, "Bạn chưa nhập đủ thông tin!Vui lòng nhập lại", "Inane error", JOptionPane.ERROR_MESSAGE);
                }else{
                HoaDon HoaDon = new HoaDon();
                HoaDon.setSoHD(t_SoHD.getText());
                HoaDon.setLyDo(t_LyDo.getText());
                HoaDon.setMSCH(t_MaCH.getText());
                HoaDon.setMSKH(t_MaKH.getText());
                
                java.util.Date utilDate1 = new java.util.Date();
                utilDate1 = tD_NgayBan.getDate();
                java.sql.Date sqlDate_NgayBan = new java.sql.Date(utilDate1.getTime());
                
                java.util.Date utilDate2 = new java.util.Date();
                utilDate1 = tD_NgayThanhToan.getDate();
                java.sql.Date sqlDate_NgayThanhToan = new java.sql.Date(utilDate2.getTime());
                HoaDon.setSoseri(t_SoSeri.getText());
                HoaDon.setMaTK(cb_TaiKhoan.getSelectedItem().toString());
                HoaDon.setThueSuat(Double.parseDouble(t_TySuatGTGT.getText()));
                double TongTong = TongTien +TongTien * Double.parseDouble(t_TySuatGTGT.getText());
                HoaDon.setTongTien(TongTong);
                
                int kqHD = BUS_HoaDon.ThemHoaDon(HoaDon.getSoHD(), sqlDate_NgayBan,  HoaDon.getLyDo(), HoaDon.getThueSuat(), sqlDate_NgayThanhToan, HoaDon.getMSCH(), HoaDon.getMSKH(), HoaDon.getMaTK(),HoaDon.getSoseri(), HoaDon.getTongTien());
                int rows = Tb_HangHoa.getRowCount();
                ArrayList<HoaDon> listView;
                listView = BUS_HoaDon.getLastIDHoaDon();
                String MaHD = null;
                int kqHH =0;
                for (HoaDon p : listView) {
                    MaHD = p.getMaHD();
                }
                for (int i = 0; i < rows; i++) {
                    Ban Ban = new Ban();
                    Ban.setMaHD(MaHD);
                    Ban.setMSHH(Tb_HangHoa.getValueAt(i, 0).toString());
                    Ban.setSoLuong(Integer.parseInt(Tb_HangHoa.getValueAt(i, 3).toString()));
                    Ban.setDonGiaBan((double) Tb_HangHoa.getValueAt(i, 4));
                    kqHH = BUS_Ban.ThemBan(Ban.getMaHD(), Ban.getMSHH(), Ban.getSoLuong(), Ban.getDonGiaBan());
                }
                BUS_Report.ReportBanHang(MaHD, t_TenCH.getText(), t_TenKH.getText(),t_DiaChiKH.getText(), t_SoHD.getText(), cb_TaiKhoan.getSelectedItem().toString(), t_MaSoThueKH.getText().toString(), t_LyDo.getText(), tD_NgayThanhToan.getDate(), t_SoSeri.getText(), t_TySuatGTGT.getText(), t_Tong.getText(), t_TinhGTGT.getText(), t_TongTien.getText(), t_TienChu.getText());
                if (kqHD == 1 && kqHH == 1) {
                    JOptionPane.showConfirmDialog(null, "Lưu thành công!", "Thông báo", -1, 1);
                } else {
                    JOptionPane.showConfirmDialog(null, "Lưu không thành công! Vui lòng thực hiện lại!", "Thông báo", -1, 2);
                }
                }
            } catch (Exception ex) {
                // ex.printStackTrace();
                JOptionPane.showConfirmDialog(null, "Lưu không thành công! Vui lòng thực hiện lại!", "Thông báo", -1, 2);
            }
        }
    }//GEN-LAST:event_btn_LuaVaInActionPerformed

    private void t_TinhGTGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_TinhGTGTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_TinhGTGTActionPerformed

    private void t_TenCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_TenCHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_TenCHActionPerformed

    private void t_TenHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_TenHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_TenHangActionPerformed

    private void t_SoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_SoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_SoLuongActionPerformed

    private void t_TySuatGTGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_TySuatGTGTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_TySuatGTGTActionPerformed

    private void t_SoSeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_SoSeriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_SoSeriActionPerformed

    private void t_LyDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_LyDoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_LyDoActionPerformed

    private void t_SoHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_SoHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_SoHDActionPerformed

    private void t_MaSoThueKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_MaSoThueKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_MaSoThueKHActionPerformed

    private void t_DiaChiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_DiaChiKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_DiaChiKHActionPerformed

    private void t_TenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_TenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_TenKHActionPerformed

    private void t_MaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_MaKHActionPerformed
        ArrayList<KhachHang> listView;
//        if (t_MaKH.getSelectedIndex() < 0) {
//            return;
//        }
        //int index=jcbphongban.getSelectedIndex();
        String mskh = t_MaKH.getText().toString();
        listView = BUS_KhachHang.getInfoKhachHangByID(mskh);
       
        if(listView.size()!= 0){
        for (KhachHang p : listView) {
            t_TenKH.setText(p.getHoTenKhach().toString());
            t_DiaChiKH.setText(p.getDiaChiKhach().toString());
            t_MaSoThueKH.setText(p.getMaSoThue().toString());
        }}
        else{
            t_TenKH.setText(null);
            t_DiaChiKH.setText(null);
            t_MaSoThueKH.setText(null);
            JOptionPane.showMessageDialog(frame, "Không tồn tại khách hàng.", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
            
        // TODO add your handling code here:
    }//GEN-LAST:event_t_MaKHActionPerformed

    private void btn_TaoKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoKHActionPerformed
        Gui_TaoKhachHang a = new Gui_TaoKhachHang();
                a.setVisible(true);
                this.setVisible(false);
                //this.dispose(); 
              
    // TODO add your handling code here:
    }//GEN-LAST:event_btn_TaoKHActionPerformed

    private void cb_MaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_MaHangActionPerformed
        ArrayList<HangHoa> listView;
        if (cb_MaHang.getSelectedIndex() < 0) {
            return;
        }
        //int index=jcbphongban.getSelectedIndex();
        String mshh = cb_MaHang.getSelectedItem().toString();
        listView = BUS_HangHoa.getInfoHangHoaByID(mshh);
        for (HangHoa p : listView) {
            t_TenHang.setText(p.getTenHang().toString());
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_MaHangActionPerformed

    private void btn_ThemHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemHangActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm thông tin này?", "Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                if(!t_SoLuong.getText().trim().equals("") || !t_DonGia.getText().trim().equals("")){
                    ArrayList<HangHoa> listView = new ArrayList();
                    listView = BUS_HangHoa.getInfoHangHoaByID(cb_MaHang.getSelectedItem().toString());
                    String MaHH;
                    String TenHang;
                    String DonViTinh;
                    DefaultTableModel model = (DefaultTableModel) Tb_HangHoa.getModel();
                    for(HangHoa p: listView){
                        MaHH = p.getMSHH().toString();
                        TenHang = p.getTenHang().toString();
                        DonViTinh = p.getDonViTinh().toString();
                        String SoLuong = t_SoLuong.getText().toString();
                        String DonGiaBan = t_DonGia.getText().toString();
                        double t = Double.parseDouble(SoLuong)*Double.parseDouble(DonGiaBan);
                        TongTien += t;
                        Locale locale = new Locale("vi","VN"); 
                        NumberFormat format = NumberFormat.getCurrencyInstance(locale);
                        double thue = Double.parseDouble(t_TySuatGTGT.getText());
                        thue = TongTien*thue;
                        t_TinhGTGT.setText(format.format(thue));
                        t_Tong.setText(format.format(TongTien));
                        double TongTong = TongTien+thue;
                        t_TongTien.setText(format.format(TongTong));
                        t_TienChu.setText(numberToString(Math.round(TongTong)));
                        model.addRow(new Object[]{MaHH, TenHang, DonViTinh, SoLuong, Double.parseDouble(DonGiaBan), t});
                        
                    }                  
                }
                else
                {
                    JOptionPane.showMessageDialog(frame, "Bạn chưa nhập số lượng hoặc đơn giá!", "Inane error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                // ex.printStackTrace();
                JOptionPane.showConfirmDialog(null, "Thêm mới không thành công! Vui lòng thực hiện lại!", "Thông báo", -1, 2);
            }
        }
    }//GEN-LAST:event_btn_ThemHangActionPerformed

    private void btn_SửaHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SửaHHActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa thông tin này?", "Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

        DefaultTableModel model = (DefaultTableModel) Tb_HangHoa.getModel();
        if(Tb_HangHoa.getSelectedRow() == -1){
            if(Tb_HangHoa.getRowCount() == 0){
                JOptionPane.showMessageDialog(frame, "Bảng không có số liệu.", "Inane error", JOptionPane.WARNING_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(frame, "Bạn phải chọn một mặt hàng", "Inane error", JOptionPane.WARNING_MESSAGE);
            }
        }else{
                    double ThanhTienLucDau;
                    ThanhTienLucDau = (double) model.getValueAt(Tb_HangHoa.getSelectedRow(),5);
                    System.out.println(ThanhTienLucDau);
                    System.out.println(TongTien);
                    TongTien = TongTien - ThanhTienLucDau;
                    System.out.println("Tong tien da tru: " + TongTien);
                    ArrayList<HangHoa> listView = new ArrayList();
                    listView = BUS_HangHoa.getInfoHangHoaByID(cb_MaHang.getSelectedItem().toString());
                    String MaHH;
                    String TenHang;
                    
                    String DonViTinh;
                    for(HangHoa p: listView){
                        
                        MaHH = p.getMSHH().toString();
                        TenHang = p.getTenHang().toString();
                        DonViTinh = p.getDonViTinh().toString();
                        String SoLuong = t_SoLuong.getText().toString();
                        String DonGiaBan = t_DonGia.getText().toString();
                        double t = Double.parseDouble(SoLuong)*Double.parseDouble(DonGiaBan);
                        model.setValueAt(MaHH, Tb_HangHoa.getSelectedRow(),0);
                        model.setValueAt(TenHang, Tb_HangHoa.getSelectedRow(),1);
                        model.setValueAt(DonViTinh, Tb_HangHoa.getSelectedRow(),2);
                        model.setValueAt(SoLuong, Tb_HangHoa.getSelectedRow(),3);
                        model.setValueAt(Double.parseDouble(DonGiaBan), Tb_HangHoa.getSelectedRow(),4);
                        model.setValueAt(t, Tb_HangHoa.getSelectedRow(),5);
                        TongTien += t;
                        Locale locale = new Locale("vi","VN"); 
                        NumberFormat format = NumberFormat.getCurrencyInstance(locale);
                        double thue = Double.parseDouble(t_TySuatGTGT.getText());
                        thue = TongTien*thue;
                        t_TinhGTGT.setText(format.format(thue));
                        t_Tong.setText(format.format(TongTien));
                        double TongTong = TongTien+thue;
                        t_TongTien.setText(format.format(TongTong));
                        t_TienChu.setText(numberToString(Math.round(TongTong)));
                    }   
        }
        }
    }//GEN-LAST:event_btn_SửaHHActionPerformed
    
    private void Tb_HangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_HangHoaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Tb_HangHoa.getModel();
        cb_MaHang.setSelectedItem(model.getValueAt(Tb_HangHoa.getSelectedRow(),0).toString());
        t_SoLuong.setText(model.getValueAt(Tb_HangHoa.getSelectedRow(),3).toString());
        t_DonGia.setText(model.getValueAt(Tb_HangHoa.getSelectedRow(),4).toString());
    }//GEN-LAST:event_Tb_HangHoaMouseClicked

    private void btn_XoaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaHangActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa thông tin này?", "Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

        DefaultTableModel model = (DefaultTableModel) Tb_HangHoa.getModel();
        if(Tb_HangHoa.getSelectedRow() == -1){
            if(Tb_HangHoa.getRowCount() == 0){
                JOptionPane.showMessageDialog(frame, "Bảng không có số liệu để xóa.", "Inane error", JOptionPane.WARNING_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(frame, "Bạn phải chọn một mặt hàng.", "Inane error", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            double ThanhTienLucDau;
            ThanhTienLucDau = (double) model.getValueAt(Tb_HangHoa.getSelectedRow(),5);

            TongTien = TongTien - ThanhTienLucDau;
            Locale locale = new Locale("vi","VN"); 
            NumberFormat format = NumberFormat.getCurrencyInstance(locale);
            double thue = Double.parseDouble(t_TySuatGTGT.getText());
            thue = TongTien*thue;
            t_TinhGTGT.setText(format.format(thue));
            t_Tong.setText(format.format(TongTien));
            double TongTong = TongTien+thue;
            t_TongTien.setText(format.format(TongTong));
            t_TienChu.setText(numberToString(Math.round(TongTong)));
            model.removeRow(Tb_HangHoa.getSelectedRow());
        }
        }
    }//GEN-LAST:event_btn_XoaHangActionPerformed

    private void cb_TaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TaiKhoanActionPerformed
        // TODO add your handling code here:
        ArrayList<TaiKhoan> listView;
        if (cb_TaiKhoan.getSelectedIndex() < 0) {
            return;
        }
        //int index=jcbphongban.getSelectedIndex();
        String MaTK = cb_TaiKhoan.getSelectedItem().toString();
        listView = BUS_TaiKhoan.getInfoTaiKhoanByID(MaTK);
        for (TaiKhoan p : listView) {
            t_TenTK.setText(p.getTenTK().toString());
        } 
    }//GEN-LAST:event_cb_TaiKhoanActionPerformed

    private void t_TenTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_TenTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_TenTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lap_Hoa_Don_Ban_Hang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lap_Hoa_Don_Ban_Hang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lap_Hoa_Don_Ban_Hang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lap_Hoa_Don_Ban_Hang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lap_Hoa_Don_Ban_Hang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tb_HangHoa;
    private javax.swing.JButton btn_LuaVaIn;
    private javax.swing.JButton btn_SửaHH;
    private javax.swing.JButton btn_TaoKH;
    private javax.swing.JButton btn_ThemHang;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_XoaHang;
    private javax.swing.JComboBox<String> cb_MaHang;
    private javax.swing.JComboBox<String> cb_TaiKhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser tD_NgayBan;
    private com.toedter.calendar.JDateChooser tD_NgayThanhToan;
    private javax.swing.JTextField t_DiaChiKH;
    private javax.swing.JTextField t_DonGia;
    private javax.swing.JTextField t_LyDo;
    private javax.swing.JTextField t_MaCH;
    private javax.swing.JTextField t_MaKH;
    private javax.swing.JTextField t_MaSoThueKH;
    private javax.swing.JTextField t_SoHD;
    private javax.swing.JTextField t_SoLuong;
    private javax.swing.JTextField t_SoSeri;
    private javax.swing.JTextField t_TenCH;
    private javax.swing.JTextField t_TenHang;
    private javax.swing.JTextField t_TenKH;
    private javax.swing.JTextField t_TenTK;
    private javax.swing.JTextField t_TienChu;
    private javax.swing.JTextField t_TinhGTGT;
    private javax.swing.JTextField t_Tong;
    private javax.swing.JTextField t_TongTien;
    private javax.swing.JTextField t_TySuatGTGT;
    // End of variables declaration//GEN-END:variables
    public static String formatNumberForRead(long number) {
        NumberFormat nf = NumberFormat.getInstance();
        String temp = nf.format(number);
        String strReturn = "";
        int slen = temp.length();
        for (int i = 0; i < slen; i++) {
            if (String.valueOf(temp.charAt(i)).equals("."))
                break;
            else if (Character.isDigit(temp.charAt(i))) {
                strReturn += String.valueOf(temp.charAt(i));
            }
        }
        return strReturn;

    }
    public static String numberToString(long number) {
        String sNumber = formatNumberForRead(number);
        // Tao mot bien tra ve
        String sReturn = "";
        // Tim chieu dai cua chuoi
        int iLen = sNumber.length();
        // Lat nguoc chuoi nay lai
        String sNumber1 = "";
        for (int i = iLen - 1; i >= 0; i--) {
            sNumber1 += sNumber.charAt(i);
        }
        // Tao mot vong lap de doc so
        // Tao mot bien nho vi tri cua sNumber
        int iRe = 0;
        do {
            // Tao mot bien cat tam
            String sCut = "";
            if (iLen > 3) {
                sCut = sNumber1.substring((iRe * 3), (iRe * 3) + 3);
                sReturn = Read(sCut, iRe) + sReturn;
                iRe++;
                iLen -= 3;
            } else {
                sCut = sNumber1.substring((iRe * 3), (iRe * 3) + iLen);
                sReturn = Read(sCut, iRe) + sReturn;
                break;
            }
        } while (true);
        if(sReturn.length() > 1){
            sReturn = sReturn.substring(0,1).toUpperCase() + sReturn.substring(1);
        }
        sReturn = sReturn + "đồng";
        return sReturn;
    }

    // Khoi tao ham Read
    public static String Read(String sNumber, int iPo) {
        // Tao mot bien tra ve
        String sReturn = "";
        // Tao mot bien so
        String sPo[] = { "", "ngàn" + " ",
                "triệu" + " ", "tỷ" + " " };
        String sSo[] = { "không" + " ", "một" + " ",
                "hai" + " ", "ba" + " ",
                "bốn" + " ", "năm" + " ",
                "sáu" + " ", "bảy" + " ",
                "tám" + " ", "chín" + " " };
        String sDonvi[] = { "", "mươi" + " ",
                "trăm" + " " };
        // Tim chieu dai cua chuoi
        int iLen = sNumber.length();
        // Tao mot bien nho vi tri doc
        int iRe = 0;
        // Tao mot vong lap de doc so
        for (int i = 0; i < iLen; i++) {
            String sTemp = "" + sNumber.charAt(i);
            int iTemp = Integer.parseInt(sTemp);
            // Tao mot bien ket qua
            String sRead = "";
            // Kiem tra xem so nhan vao co = 0 hay ko
            if (iTemp == 0) {
                switch (iRe) {
                case 0:
                    break;// Khong lam gi ca
                case 1: {
                    if (Integer.parseInt("" + sNumber.charAt(0)) != 0) {
                        sRead = "lẻ" + " ";
                    }
                    break;
                }
                case 2: {
                    if (Integer.parseInt("" + sNumber.charAt(0)) != 0
                            && Integer.parseInt("" + sNumber.charAt(1)) != 0) {
                        sRead = "không trăm" + " ";
                    }
                    break;
                }
                }
            } else if (iTemp == 1) {
                switch (iRe) {
                case 1:
                    sRead = "mười" + " ";
                    break;
                default:
                    sRead = "một" + " " + sDonvi[iRe];
                    break;
                }
            } else if (iTemp == 5) {
                switch (iRe) {
                case 0: {
                    if(sNumber.length() <= 1){
                        sRead = "năm" + " ";
                    }
                    else if (Integer.parseInt("" + sNumber.charAt(1)) != 0) {
                        sRead = "lăm" + " ";
                    } else
                        sRead = "năm" + " ";
                    break;
                }
                default:
                    sRead = sSo[iTemp] + sDonvi[iRe];
                }
            } else {
                sRead = sSo[iTemp] + sDonvi[iRe];
            }

            sReturn = sRead + sReturn;
            iRe++;
        }
        if (sReturn.length() > 0) {
            sReturn += sPo[iPo];
        }

        return sReturn;
    }

    public static String getRomanNumerals(int Int) {
        LinkedHashMap<String, Integer> roman_numerals = new LinkedHashMap<String, Integer>();
        roman_numerals.put("M", 1000);
        roman_numerals.put("CM", 900);
        roman_numerals.put("D", 500);
        roman_numerals.put("CD", 400);
        roman_numerals.put("C", 100);
        roman_numerals.put("XC", 90);
        roman_numerals.put("L", 50);
        roman_numerals.put("XL", 40);
        roman_numerals.put("X", 10);
        roman_numerals.put("IX", 9);
        roman_numerals.put("V", 5);
        roman_numerals.put("IV", 4);
        roman_numerals.put("I", 1);
        String res = "";
        for(Map.Entry<String, Integer> entry : roman_numerals.entrySet()){
          int matches = Int/entry.getValue();
          res += repeat(entry.getKey(), matches);
          Int = Int % entry.getValue();
        }
        return res;
    }
    public static String repeat(String s, int n) {
        if(s == null) {
            return null;
        }
        final StringBuilder sb = new StringBuilder();
        for(int i = 0; i < n; i++) {
            sb.append(s);
        }
        return sb.toString();
    }
}
